import { useEffect } from 'react'
import { motion } from 'motion/react'
import { HexLogo } from '@/components/ui/SentinelLogo'
import { Link } from 'react-router-dom'

const GLOSSARY = [
  { term: 'Whale', def: 'An Ethereum wallet that moves large amounts of capital — typically market makers, funds, or protocols with a history of profitable trades.' },
  { term: 'Signal', def: 'A directional assessment (BULLISH / BEARISH / NEUTRAL) generated by Claude AI based on recent whale wallet behavior.' },
  { term: 'Profit Factor (PF)', def: 'Total gains divided by total losses over a period. PF of 2.0 means you made $2 for every $1 lost. 2.0+ is considered strong.' },
  { term: 'Win Rate (Win%)', def: 'Percentage of trades that closed at a profit. 60%+ is considered a strong track record.' },
  { term: 'Max Drawdown (Max DD)', def: 'The largest peak-to-trough loss experienced. Lower is better — indicates how much the trader\'s portfolio dropped at its worst point.' },
  { term: 'Track Record', def: 'The number of days of verified on-chain trading history. Longer track records provide more statistical confidence.' },
  { term: 'Copy Trading', def: 'Executing the same trade as a tracked whale wallet, at your own size, using your own wallet. Hadaleum is non-custodial — your keys never leave your control.' },
  { term: 'Non-custodial', def: 'You retain full control of your private keys. Hadaleum never holds, accesses, or stores your funds.' },
  { term: 'DEX', def: 'Decentralized Exchange — a platform where tokens are traded on-chain via smart contracts, without a central intermediary. Examples: Uniswap, Curve.' },
  { term: 'Hadaleum Score', def: 'A composite score (0–100) that weights win rate, profit factor, track record length, and drawdown control. Higher is better.' },
  { term: 'BULLISH', def: 'Whales are accumulating — buying or moving assets into positions. Historically associated with upward price pressure.' },
  { term: 'BEARISH', def: 'Whales are distributing — selling or moving assets out of positions. Historically associated with downward price pressure.' },
  { term: 'MetaMask', def: 'A browser-based Ethereum wallet that Hadaleum uses to execute copy trades. You always approve transactions yourself.' },
]

const DATA_SOURCES = [
  { name: 'Dune Analytics', role: 'Whale wallet rankings and DEX trader performance data', url: 'https://dune.com' },
  { name: 'DefiLlama', role: 'Best-rate DEX swap routing across all liquidity venues', url: 'https://defillama.com' },
  { name: 'CoinGecko', role: 'ETH price, market data, and ecosystem token information', url: 'https://coingecko.com' },
  { name: 'Anthropic Claude', role: 'AI signal generation — BULLISH/BEARISH/NEUTRAL analysis with reasoning', url: 'https://anthropic.com' },
  { name: 'Etherscan', role: 'On-chain transaction verification and wallet history', url: 'https://etherscan.io' },
]

export default function AboutPage() {
  useEffect(() => { document.title = 'About — Hadaleum' }, [])

  return (
    <div className="min-h-screen bg-bg-base py-16 px-4">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-3xl mx-auto space-y-16"
      >
        {/* Header */}
        <div className="flex items-center gap-4">
          <HexLogo size={40} />
          <div>
            <h1 className="font-display text-3xl font-bold text-text-primary">About Hadaleum</h1>
            <p className="text-text-muted text-sm mt-1">ha-DAL-ee-um · The arena of the deepest intelligence.</p>
          </div>
        </div>

        {/* Mission */}
        <section>
          <h2 className="font-display text-xl font-bold text-text-primary mb-4">What we do</h2>
          <p className="text-text-secondary leading-relaxed mb-3">
            Hadaleum tracks 2,796 elite Ethereum wallets that have demonstrated consistent, profitable trading behavior over 90+ days. We analyze their on-chain activity using Claude AI and surface actionable signals — without ever touching your funds.
          </p>
          <p className="text-text-secondary leading-relaxed">
            The core value: <strong className="text-text-primary">copy smart money trades without giving up custody of your keys.</strong> No competitor offers non-custodial copy trading with AI-filtered whale signals. That is the moat.
          </p>
        </section>

        {/* Data Sources */}
        <section>
          <h2 className="font-display text-xl font-bold text-text-primary mb-4">Data sources</h2>
          <div className="space-y-3">
            {DATA_SOURCES.map(({ name, role, url }) => (
              <div key={name} className="flex items-start gap-4 p-4 rounded-xl border border-border-default bg-bg-surface">
                <div className="flex-1 min-w-0">
                  <a href={url} target="_blank" rel="noopener noreferrer" className="font-medium text-text-primary text-sm hover:text-green transition-colors">
                    {name} ↗
                  </a>
                  <p className="text-xs text-text-muted mt-0.5">{role}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Methodology */}
        <section>
          <h2 className="font-display text-xl font-bold text-text-primary mb-4">Scoring methodology</h2>
          <div className="rounded-xl border border-border-default bg-bg-surface p-5 space-y-3 text-sm text-text-secondary leading-relaxed">
            <p>The Hadaleum Score (0–100) is a composite rank weighting four dimensions:</p>
            <ul className="space-y-2 ml-4">
              <li><strong className="text-text-primary">Win Rate (30%)</strong> — percentage of profitable trades over 90+ days</li>
              <li><strong className="text-text-primary">Profit Factor (30%)</strong> — total gains / total losses</li>
              <li><strong className="text-text-primary">Max Drawdown (20%)</strong> — worst peak-to-trough loss (lower = better)</li>
              <li><strong className="text-text-primary">Track Record (20%)</strong> — days of verified history (longer = more confidence)</li>
            </ul>
            <p className="text-xs text-text-muted pt-2">
              Wallets with fewer than 90 days of history or fewer than 50 trades are excluded. Exchange hot wallets, MEV bots (&gt;100 trades/day), and known custodial addresses are filtered out.
            </p>
          </div>
        </section>

        {/* Glossary */}
        <section id="glossary">
          <h2 className="font-display text-xl font-bold text-text-primary mb-4">Glossary</h2>
          <div className="space-y-3">
            {GLOSSARY.map(({ term, def }) => (
              <div key={term} className="flex gap-4 py-3 border-b border-border-subtle last:border-0">
                <div className="w-36 flex-shrink-0">
                  <span className="text-sm font-semibold text-green">{term}</span>
                </div>
                <p className="text-sm text-text-secondary flex-1">{def}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Links */}
        <div className="flex flex-wrap gap-4 text-sm text-text-muted pt-4 border-t border-border-subtle">
          <Link to="/privacy" className="hover:text-text-secondary">Privacy Policy</Link>
          <Link to="/terms" className="hover:text-text-secondary">Terms of Service</Link>
          <Link to="/disclaimer" className="hover:text-text-secondary">Disclaimer</Link>
          <Link to="/" className="hover:text-text-secondary">← Home</Link>
        </div>
      </motion.div>
    </div>
  )
}
