import { useEffect, useState } from 'react'
import { motion, AnimatePresence } from 'motion/react'
import { X, ChevronRight, Waves, Zap, Shield } from 'lucide-react'
import { useNavigate } from 'react-router-dom'

const STORAGE_KEY = 'hadaleum_onboarding_v1'

const STEPS = [
  {
    icon: Waves,
    title: 'What is a whale?',
    body: 'A "whale" is an Ethereum wallet that moves large amounts of ETH or tokens — market makers, funds, and protocols that historically make profitable trades. Hadaleum tracks 2,796 of the best-performing ones.',
    tip: '"Smart money" is institutional or expert capital that often moves before the market follows.',
  },
  {
    icon: Zap,
    title: 'What is a signal?',
    body: 'A signal is a direction (BULLISH, BEARISH, or NEUTRAL) generated by Claude AI after analyzing recent whale behavior. BULLISH means whales are accumulating — a possible upward move. BEARISH means they\'re distributing — a possible decline.',
    tip: 'Signals are informational only. They are not financial advice. Past accuracy does not guarantee future results.',
  },
  {
    icon: Shield,
    title: 'How do I copy a trade?',
    body: 'On the Invest page, you see live whale moves. Click "Copy trade", set your amount, and MetaMask executes the swap on-chain. Hadaleum never holds your funds — you stay in full custody at all times.',
    tip: 'You can simulate copy trades without a wallet by setting your amount and reviewing the quote. Connect MetaMask only when ready to execute.',
  },
]

export default function OnboardingModal() {
  const [visible, setVisible] = useState(false)
  const [step, setStep] = useState(0)
  const navigate = useNavigate()

  useEffect(() => {
    try {
      const done = localStorage.getItem(STORAGE_KEY)
      if (!done) setVisible(true)
    } catch {}
  }, [])

  function dismiss() {
    try { localStorage.setItem(STORAGE_KEY, '1') } catch {}
    setVisible(false)
  }

  function next() {
    if (step < STEPS.length - 1) {
      setStep((s) => s + 1)
    } else {
      dismiss()
    }
  }

  function goToGlossary() {
    dismiss()
    navigate('/about#glossary')
  }

  if (!visible) return null

  const current = STEPS[step]
  const Icon = current.icon

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="absolute inset-0 bg-black/60 backdrop-blur-sm"
          onClick={dismiss}
        />
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 16 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 16 }}
          transition={{ type: 'spring', stiffness: 350, damping: 28 }}
          className="relative w-full max-w-md rounded-2xl border border-border-default bg-bg-surface shadow-card p-6 z-10"
        >
          <button
            type="button"
            onClick={dismiss}
            className="absolute top-4 right-4 text-text-muted hover:text-text-secondary transition-colors"
          >
            <X className="h-4 w-4" />
          </button>

          {/* Header */}
          <div className="flex items-center gap-2 mb-6">
            <div className="flex gap-1.5">
              {STEPS.map((_, i) => (
                <div
                  key={i}
                  className={`h-1 rounded-full transition-all ${i === step ? 'w-6 bg-green' : i < step ? 'w-3 bg-green/40' : 'w-3 bg-white/10'}`}
                />
              ))}
            </div>
            <span className="text-[10px] text-text-muted ml-1">{step + 1} / {STEPS.length}</span>
          </div>

          {/* Step content */}
          <AnimatePresence mode="wait">
            <motion.div
              key={step}
              initial={{ opacity: 0, x: 12 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -12 }}
              transition={{ duration: 0.2 }}
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-green/10 border border-green/20">
                  <Icon className="h-5 w-5 text-green" />
                </div>
                <h2 className="font-display text-xl font-bold text-text-primary">{current.title}</h2>
              </div>
              <p className="text-sm text-text-secondary leading-relaxed mb-4">{current.body}</p>
              <div className="rounded-xl border border-border-subtle bg-bg-overlay px-4 py-3">
                <p className="text-[11px] text-text-muted leading-relaxed">{current.tip}</p>
              </div>
            </motion.div>
          </AnimatePresence>

          {/* Actions */}
          <div className="flex items-center gap-3 mt-6">
            <button
              type="button"
              onClick={dismiss}
              className="text-sm text-text-muted hover:text-text-secondary transition-colors"
            >
              Skip
            </button>
            <div className="flex-1" />
            <button
              type="button"
              onClick={goToGlossary}
              className="text-sm text-green hover:underline"
            >
              Glossary →
            </button>
            <button
              type="button"
              onClick={next}
              className="flex items-center gap-2 rounded-xl bg-green px-4 py-2 text-sm font-semibold text-text-inverse shadow-glow hover:bg-green-bright transition-colors"
            >
              {step < STEPS.length - 1 ? 'Next' : 'Get started'}
              <ChevronRight className="h-3.5 w-3.5" />
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  )
}
